/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2cf52559-f6b3-42ba-b7bc-6f9b9090e51f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_om1xletLK",
    "aws_user_pools_web_client_id": "764a2dfgcvbr7cuei70iumf8n4",
    "oauth": {
        "domain": "rnamplify942f7465-942f7465-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
